feat: add normalized plip data
nossas/bonde-apis pull request #80
Opened 2023-02-02 12:46 UTC by gloriateodoro

2023-02-03 14:01 UTC, igr-santos requested changes

2023-02-03 14:01 UTC, igr-santos commented on action-network/web/normalize.py
> +        expected_signatures=form_data.expected_signatures,
@gloriateodoro ficou faltando adicionar o tipo da ficha que por enquanto vai ser padrão: Voluntário

2023-02-03 15:07 UTC, igr-santos approved these changes

2023-02-07 14:08 UTC, dieh approved these changes

2023-02-07 14:09 UTC, igr-santos approved these changes

2023-02-07 14:11 UTC, merged